"""Pydantic v2 data contracts for pipeline communication."""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class EntityType(str, Enum):
    PERSON = "PERSON"
    ORG = "ORG"
    GPE = "GPE"
    NORP = "NORP"
    FAC = "FAC"
    EVENT = "EVENT"
    PRODUCT = "PRODUCT"
    LOC = "LOC"
    WEAPON_SYSTEM = "WEAPON_SYSTEM"
    FACILITY = "FACILITY"


class AlertType(str, Enum):
    # Legacy (kept for backward compat with existing DB rows)
    KEYWORD = "keyword"
    ANOMALY = "anomaly"
    TREND = "trend"
    THRESHOLD = "threshold"
    COMPOUND = "compound"
    # New state-transition alert types
    IW_THRESHOLD = "iw_threshold"
    CORROBORATION_CHANGE = "corroboration_change"
    FUSION_CONVERGENCE = "fusion_convergence"
    ASSESSMENT_CONTRADICTION = "assessment_contradiction"
    NEW_EVENT_CLUSTER = "new_event_cluster"
    SOURCE_SILENCE_BREAK = "source_silence_break"
    ENTITY_EMERGENCE = "entity_emergence"
    COORDINATED_POSTING = "coordinated_posting"
    SIGNAL_GAP_OPENED = "signal_gap_opened"
    SIGNAL_GAP_CLOSED = "signal_gap_closed"
    SOURCE_FAILURE = "source_failure"
    INFRA_ANOMALY = "infra_anomaly"
    FIRST_REPORT = "first_report"


class BriefingType(str, Enum):
    DAILY = "daily"
    FLASH = "flash"
    WEEKLY = "weekly"
    DELTA = "delta"


class EntityRole(str, Enum):
    SUBJECT = "SUBJECT"
    OBJECT = "OBJECT"
    LOCATION = "LOCATION"


# ---------------------------------------------------------------------------
# Pipeline data contracts
# ---------------------------------------------------------------------------

class RawItemModel(BaseModel):
    """Item as collected from a source, before processing."""
    title: str
    content: str = ""
    url: str = ""
    published_at: Optional[datetime] = None
    source_name: str = ""
    source_type: str = "rss"
    external_id: Optional[str] = None
    fetched_at: datetime = Field(default_factory=datetime.utcnow)


class ExtractedEntity(BaseModel):
    """Entity extracted from an item by NLP."""
    text: str
    entity_type: EntityType
    role: EntityRole = EntityRole.SUBJECT
    confidence: float = 1.0
    canonical_name: Optional[str] = None


class ProcessedItem(BaseModel):
    """Item after NLP + scoring + entity extraction."""
    raw_item: RawItemModel
    content_hash: str = ""
    entities: list[ExtractedEntity] = Field(default_factory=list)
    severity_score: float = 0.0
    keyword_score: float = 0.0
    entity_salience: float = 0.0
    novelty_score: float = 1.0
    region: Optional[str] = None
    is_duplicate: bool = False
    duplicate_of_id: Optional[int] = None
    embedding: Optional[list[float]] = None


class ClaimModel(BaseModel):
    """A factual claim extracted from a source item."""
    subject: str
    verb: str
    object: str = ""
    claim_text: str
    claim_type: str = "assertion"
    source_name: str = ""
    confidence: float = 1.0


class EventCluster(BaseModel):
    """A cluster of items representing a single real-world event."""
    summary: str
    event_type: Optional[str] = None
    severity: float = 0.0
    item_ids: list[int] = Field(default_factory=list)
    entity_names: list[str] = Field(default_factory=list)
    region: Optional[str] = None
    location_name: Optional[str] = None
    lat: Optional[float] = None
    lon: Optional[float] = None


class AlertModel(BaseModel):
    """Alert generated by the alerting engine."""
    alert_type: AlertType
    severity: float
    title: str
    detail: str = ""
    event_id: Optional[int] = None
    item_id: Optional[int] = None
    delivered_via: Optional[str] = None


class BriefingRequest(BaseModel):
    """Request to generate a briefing."""
    briefing_type: BriefingType = BriefingType.DAILY
    hours_back: int = 24
    model: Optional[str] = None


class BriefingResult(BaseModel):
    """Generated briefing."""
    briefing_type: BriefingType
    content_md: str
    model_used: str
    covering_from: datetime
    covering_to: datetime


class TrendPoint(BaseModel):
    """A single trend measurement."""
    entity_name: str
    metric_name: str
    metric_value: float
    window_start: datetime
    window_end: datetime
    is_anomaly: bool = False
    sigma: float = 0.0
